### ISSUE TITLE
CLI: use argparse to accept input directly from shell

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/mathinterpreter#15]

**Comment by hsguidi** [comment]
I am wondering how this should be done.
A)  mathinterpreter "-1+5/ 3"
B)  mathinterpreter -1+5/ 3
C) BOTH ABOVE
D) mathinterpreter -i inputfile.txt -o outputfile.txt

**Comment by aureliobarbosa** [comment]
I was thinking about using A)

**Comment by aureliobarbosa** [comment]
Hey @hsguidi. I ended up implementing option C). 

There is an small issue with, in that bash complains about as indicated below:
```bash
❯ mathinterpreter  1 +2/(  3)
bash: syntax error near unexpected token `('
```

Because of that it was necessary to mention that in the help, that it is necessary to use single or double quotes while calling `mathinterpreter` with expressions as inputs. More details on the PR.
