### ISSUE TITLE
Verbose version on CLI (--help --version)

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/mathinterpreter#74]
Currently this project doesn't show up 

Currently math interpreter doesn't show it's version number on the help message. It also doesn't have a `--version` option. 
Maybe we could include it, for consistenc7.

```bash
❯ mathinterpreter --help
usage: mathinterpreter [-h] [expression ...]

A simple math interpreter with a command line interface and an interactive mode.

positional arguments:
  expression  Evaluate expression, which must be in one of the following forms:
                1+1/2^4
                1 + 1 / 2^4
                1 + 1 / '(2^(4/2))'
              Note that to properly include parenthesis on command line calls it is necessary to use single or double quotes, ' or ", enclosing the expression.
              Default: interactive mode.

options:
  -h, --help  show this help message and exit
```

**Comment by hsguidi** [comment]
Although it is a nice standard for programs to accept command line arguments like '-h', '--help', '-V', and '--version', I believe this will decrease usability for this particular project. That said, I can include this feature, but it would be easier and clearer to encapsulate the mathematical expression inside double quotes.

**Comment by aureliobarbosa** [comment]
I think you have brought two points on this question. 

1) --version is an standard, and can be implemented.  Nevertheless, if got to supersed all other options, including --help and the other parameters. 

As an example, take a look on `grep --version --help`, only the `--version` option is displayed.

How that would decrease usability?

You are discussing the possibility off a user typing something like:

```bash
mathinterpreter 1 + 2 + --version
```
Which is non-sense but would output the version and not give an error message?

**Comment by aureliobarbosa** [comment]
Anyway, I don't think it is so important.
